import type { OnboardingStep, OnboardingTourConfig } from './types'

const kbSteps: OnboardingStep[] = [
  // Knowledge base
  {
    target: '[data-testid="nav-kb"]',
    content: 'onboarding.step6.description',
    title: 'onboarding.step6.title',
    placement: 'auto',
    route: '/app/kb',
    advanceOnClick: true,
    waitForRouteChange: true,
  },
  {
    target: '[data-testid="kb-import-button"]',
    content: 'onboarding.step7b.description',
    title: 'onboarding.step7b.title',
    placement: 'auto',
    route: '/app/kb',
  },
  {
    target: '[data-testid="kb-create-card"]',
    content: 'onboarding.step7.description',
    title: 'onboarding.step7.title',
    placement: 'auto',
    route: '/app/kb',
    advanceOnClick: true,
    overlayClickAction: false,
  },
  {
    target: '[data-testid="kb-dialog-name"]',
    content: 'onboarding.step7a.description',
    title: 'onboarding.step7a.title',
    placement: 'bottom',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="kb-dialog-description"]',
    content: 'onboarding.step7c.description',
    title: 'onboarding.step7c.title',
    placement: 'bottom',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="kb-dialog-embedding"]',
    content: 'onboarding.step7d.description',
    title: 'onboarding.step7d.title',
    placement: 'bottom',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="kb-dialog-rerank-model"]',
    content: 'onboarding.step7f.description',
    title: 'onboarding.step7f.title',
    placement: 'bottom',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="kb-dialog-chunk-settings"]',
    content: 'onboarding.step7g.description',
    title: 'onboarding.step7g.title',
    placement: 'bottom',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="kb-dialog-separator"]',
    content: 'onboarding.step7h.description',
    title: 'onboarding.step7h.title',
    placement: 'bottom',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="kb-dialog-rerank-section"]',
    content: 'onboarding.step7i.description',
    title: 'onboarding.step7i.title',
    placement: 'bottom',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="kb-dialog-rerank-enabled"]',
    content: 'onboarding.step7j.description',
    title: 'onboarding.step7j.title',
    placement: 'left',
    skipScroll: true,
    overlayClickAction: false,
  },
  {
    target: '[data-testid="kb-dialog-rerank-params"]',
    content: 'onboarding.step7k.description',
    title: 'onboarding.step7k.title',
    placement: 'bottom',
    skipScroll: true,
    overlayClickAction: false,
  },
  {
    target: '[data-testid="kb-dialog-submit"]',
    content: 'onboarding.step7e.description',
    title: 'onboarding.step7e.title',
    placement: 'top',
    route: '/app/kb',
    advanceOnClick: true,
    waitForRouteChange: true,
    overlayClickAction: false,
  },
  {
    target: '[data-testid="kb-detail-page"]',
    content: 'onboarding.step31a.description',
    title: 'onboarding.step31a.title',
    placement: 'center',
    route: '/app/kb',
  },
  {
    target: '[data-testid="kb-upload-button"]',
    content: 'onboarding.step31b.description',
    title: 'onboarding.step31b.title',
    placement: 'auto',
    route: '/app/kb',
    advanceOnClick: true,
    overlayClickAction: false,
  },
  {
    target: '[data-testid="kb-upload-dialog"]',
    content: 'onboarding.step31c.description',
    title: 'onboarding.step31c.title',
    placement: 'bottom',
    route: '/app/kb',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="kb-upload-dialog-cancel"]',
    content: 'onboarding.step31d.description',
    title: 'onboarding.step31d.title',
    placement: 'top',
    route: '/app/kb',
    advanceOnClick: true,
    overlayClickAction: false,
  },
  {
    target: '[data-testid="kb-import-url-button"]',
    content: 'onboarding.step31e.description',
    title: 'onboarding.step31e.title',
    placement: 'auto',
    route: '/app/kb',
    advanceOnClick: true,
    overlayClickAction: false,
  },
  {
    target: '[data-testid="kb-import-url-dialog"]',
    content: 'onboarding.step31f.description',
    title: 'onboarding.step31f.title',
    placement: 'bottom',
    route: '/app/kb',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="kb-import-url-dialog-cancel"]',
    content: 'onboarding.step31g.description',
    title: 'onboarding.step31g.title',
    placement: 'top',
    route: '/app/kb',
    advanceOnClick: true,
    overlayClickAction: false,
  },
  {
    target: '[data-testid="kb-documents-table"]',
    content: 'onboarding.step31h.description',
    title: 'onboarding.step31h.title',
    placement: 'top',
    route: '/app/kb',
  },
  {
    target: '[data-testid="kb-search-test-button"]',
    content: 'onboarding.step31l.description',
    title: 'onboarding.step31l.title',
    placement: 'auto',
    route: '/app/kb',
    advanceOnClick: true,
    waitForRouteChange: true,
    overlayClickAction: false,
  },
  {
    target: '[data-testid="kb-search-lab"]',
    content: 'onboarding.step31m.description',
    title: 'onboarding.step31m.title',
    placement: 'center',
    route: '/app/kb',
  },
  {
    target: '[data-testid="kb-search-query"]',
    content: 'onboarding.step31n.description',
    title: 'onboarding.step31n.title',
    placement: 'top',
    route: '/app/kb',
  },
  {
    target: '[data-testid="kb-search-submit"]',
    content: 'onboarding.step31o.description',
    title: 'onboarding.step31o.title',
    placement: 'top',
    route: '/app/kb',
    advanceOnClick: true,
  },
  {
    target: '[data-testid="kb-search-results"]',
    content: 'onboarding.step31p.description',
    title: 'onboarding.step31p.title',
    placement: 'top',
    route: '/app/kb',
  },
]
export const kbTourConfig: OnboardingTourConfig = {
  id: 'kb',
  title: 'onboarding.tourKBTitle',
  description: 'onboarding.tourKBDescription',
  steps: kbSteps,
  autoStart: false,
}
