import type { OnboardingStep, OnboardingTourConfig } from './types'

const workflowConfigSteps: OnboardingStep[] = [
  {
    target: '[data-testid="workflow-canvas"]',
    content: 'onboarding.step20a.description',
    title: 'onboarding.step20a.title',
    placement: 'center',
    overlayClickAction: false,
    skipIfMissing: true,
  },
  {
    target: '[data-testid="workflow-edit-mode-controls"]',
    content: 'onboarding.step20b.description',
    title: 'onboarding.step20b.title',
    placement: 'right',
    overlayClickAction: false,
    skipIfMissing: true,
  },
  {
    target: '[data-testid="workflow-add-node-button"]',
    content: 'onboarding.step20c.description',
    title: 'onboarding.step20c.title',
    placement: 'right',
    overlayClickAction: false,
    skipIfMissing: true,
  },
  {
    target: '[data-testid^="workflow-node-"] .react-flow__handle',
    content: 'onboarding.step20d.description',
    title: 'onboarding.step20d.title',
    placement: 'auto',
    overlayClickAction: false,
    skipIfMissing: true,
  },
  {
    target: '[data-testid^="workflow-node-"]',
    content: 'onboarding.step20e.description',
    title: 'onboarding.step20e.title',
    placement: 'auto',
    overlayClickAction: false,
    skipIfMissing: true,
  },
  {
    target: '[data-testid="workflow-validation-checklist"]',
    content: 'onboarding.step20f.description',
    title: 'onboarding.step20f.title',
    placement: 'bottom',
    overlayClickAction: false,
    skipIfMissing: true,
  },
  {
    target: '[data-testid="workflow-run-button"]',
    content: 'onboarding.step20g.description',
    title: 'onboarding.step20g.title',
    placement: 'bottom',
    overlayClickAction: false,
    skipIfMissing: true,
  },
  {
    target: '[data-testid="workflow-save-button"]',
    content: 'onboarding.step20h.description',
    title: 'onboarding.step20h.title',
    placement: 'bottom',
    overlayClickAction: false,
    skipIfMissing: true,
  },
  {
    target: '[data-testid="workflow-settings-button"]',
    content: 'onboarding.step20i.description',
    title: 'onboarding.step20i.title',
    placement: 'bottom',
    overlayClickAction: false,
    skipIfMissing: true,
  },
  {
    target: '[data-testid="workflow-embed-button"]',
    content: 'onboarding.step20j.description',
    title: 'onboarding.step20j.title',
    placement: 'bottom',
    overlayClickAction: false,
    skipIfMissing: true,
  },
  {
    target: '[data-testid="workflow-publish-button"]',
    content: 'onboarding.step20k.description',
    title: 'onboarding.step20k.title',
    placement: 'bottom',
    overlayClickAction: false,
    skipIfMissing: true,
  },
]

export const workflowConfigTourConfig: OnboardingTourConfig = {
  id: 'workflowConfig',
  title: 'onboarding.tourWorkflowConfigTitle',
  description: 'onboarding.tourWorkflowConfigDescription',
  steps: workflowConfigSteps,
  autoStart: false,
}
